---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tarunlablel
  labels:
    app: tarunlablel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tarunlablel
  template:
    metadata:
      labels:
        app: tarunlablel
    spec:
      containers:
      - name: taruncontainer
        image: 560391603062.dkr.ecr.ap-southeast-1.amazonaws.com/ttiwari1005/project18:latest
        ports:
        - containerPort: 3000
...
