---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tarunlablel
  labels:
    app: tarunlablel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tarunlablel
  template:
    metadata:
      labels:
        app: tarunlablel
    spec:
      containers:
      - name: taruncontainer
        image: ttiwari1005/Devops-on-OTT-platform
        ports:
        - containerPort: 3000
...
