---
apiVersion: v1
kind: Service
metadata:
  name: tarunlablel
  labels:
    app: tarunlablel
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: tarunlablel
  type: LoadBalancer
...
